In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from transformers import pipeline
import re
import string
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

In [5]:
data_fake = pd.read_csv("Fake.csv")
data_true = pd.read_csv("True.csv")

In [6]:
data_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [7]:
data_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [8]:
data_fake["class"]=0
data_true["class"]=1

In [9]:
data_fake.shape,data_true.shape

((23481, 5), (21417, 5))

In [10]:
data_fake_manual_testing = data_fake.tail(10)
for i in range(23480,23470,-1):
    data_fake.drop([i],axis=0,inplace=True)

data_true_manual_testing = data_true.tail(10)
for i in range(21416,21406,-1):
    data_true.drop([i],axis=0,inplace=True)

In [11]:
data_fake.shape,data_true.shape

((23471, 5), (21407, 5))

In [12]:
data_fake_manual_testing["class"]=0
data_true_manual_testing["class"]=1

/tmp/ipykernel_10771/1040235159.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fake_manual_testing["class"]=0
/tmp/ipykernel_10771/1040235159.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_true_manual_testing["class"]=1

In [13]:
data_fake_manual_testing.head()

,title,text,subject,date,class
23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",0
23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",0
23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",0
23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",0
23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",0

In [14]:
data_true_manual_testing.head()

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1

In [15]:
data_merge = pd.concat([data_fake,data_true],axis=0)
data_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [16]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [17]:
data=data_merge.drop(["title","subject","date"],axis=1)

In [18]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [19]:
data=data.sample(frac=1)

In [20]:
data.head()

                                                   text  class
7218  If there were a contest to describe who the mo...      0
7519  ABOARD AIR FORCE ONE (Reuters) - President Bar...      1
5551  TOKYO (Reuters) - Japanese Prime Minister Shin...      1
539   Donald Trump s horrific defense of white supre...      0
613   It was just revealed today that Federal agents...      0

In [21]:
data.reset_index(inplace=True)
data.drop(["index"],axis=1,inplace=True)

In [22]:
data.columns

Index(['text', 'class'], dtype='object')

In [23]:
data.head()

                                                text  class
0  If there were a contest to describe who the mo...      0
1  ABOARD AIR FORCE ONE (Reuters) - President Bar...      1
2  TOKYO (Reuters) - Japanese Prime Minister Shin...      1
3  Donald Trump s horrific defense of white supre...      0
4  It was just revealed today that Federal agents...      0

In [24]:
def wordopt(text):
    text=text.lower()
    text=re.sub(r'\[.*?\]','',text)
    text=re.sub(r'\W',' ',text)
    text=re.sub(r'https?://\S+|www\.\S+','',text)
    text=re.sub(r'<.*?>+','',text)
    text=re.sub(r'[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub(r'\n','',text)
    text=re.sub(r'\w*\d\w*','',text)
    return text

In [25]:
data['text']=data['text'].apply(wordopt)

In [26]:
x=data['text']
y=data['class']

In [27]:
emotion_classifier = pipeline("text-classification", model="bhadresh-savani/distilbert-base-uncased-emotion", return_all_scores=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization=TfidfVectorizer()
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)

In [30]:
from sklearn.model_selection import cross_val_score

def evaluate_model_cv(model, name):
    print(f"\n📊 Cross-Validation for {name}:")
    scores = cross_val_score(model, xv_train, y_train, cv=5, scoring='accuracy')
    print(f"Accuracy Scores: {np.round(scores, 4)}")
    print(f"Mean Accuracy: {scores.mean():.4f}")
    print(f"Standard Deviation: {scores.std():.4f}")

# Evaluate each model using cross-validation
evaluate_model_cv(LogisticRegression(), "Logistic Regression")
evaluate_model_cv(DecisionTreeClassifier(), "Decision Tree")
evaluate_model_cv(GradientBoostingClassifier(random_state=0), "Gradient Boosting")
evaluate_model_cv(RandomForestClassifier(random_state=0), "Random Forest")

📊 Cross-Validation for Logistic Regression:
Accuracy Scores: [0.9854 0.9838 0.9844 0.985  0.9823]
Mean Accuracy: 0.9842
Standard Deviation: 0.0011

📊 Cross-Validation for Decision Tree:
Accuracy Scores: [0.9945 0.9948 0.9963 0.9939 0.9939]
Mean Accuracy: 0.9947
Standard Deviation: 0.0009

📊 Cross-Validation for Gradient Boosting:
Accuracy Scores: [0.9951 0.9947 0.9967 0.9954 0.9949]
Mean Accuracy: 0.9954
Standard Deviation: 0.0007

📊 Cross-Validation for Random Forest:
Accuracy Scores: [0.9828 0.9865 0.9887 0.9844 0.9862]
Mean Accuracy: 0.9857
Standard Deviation: 0.0020

In [31]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [32]:
pred_lr=LR.predict(xv_test)

In [33]:
LR.score(xv_test,y_test)

0.9875222816399287

In [34]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5934
           1       0.98      0.99      0.99      5286

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [35]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [36]:
pred_dt=DT.predict(xv_test)

In [37]:
DT.score(xv_test,y_test)

0.9955436720142602

In [38]:
print(classification_report(y_test,pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5934
           1       1.00      0.99      1.00      5286

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220

In [39]:
from sklearn.ensemble import GradientBoostingClassifier
GB=GradientBoostingClassifier(random_state=0)
GB.fit(xv_train,y_train)

GradientBoostingClassifier(random_state=0)

In [40]:
pred_gb=GB.predict(xv_test)

In [41]:
GB.score(xv_test,y_test)

0.9947415329768271

In [42]:
print(classification_report(y_test,pred_gb))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5934
           1       0.99      1.00      0.99      5286

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [43]:
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(random_state=0)
RF.fit(xv_train,y_train)

RandomForestClassifier(random_state=0)

In [44]:
pred_rf=RF.predict(xv_test)

In [45]:
RF.score(xv_test,y_test)

0.9893048128342246

In [46]:
print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5934
           1       0.99      0.99      0.99      5286

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [50]:
def get_emotion_scores(text):
    results = emotion_classifier(text[:512])  # Limit input to avoid truncation

    # Expected format: results = [[{'label': 'emotion', 'score': float}, ...]]
    # Validate the structure of results to prevent TypeError
    if not (isinstance(results, list) and
            len(results) > 0 and
            isinstance(results[0], list) and
            len(results[0]) > 0 and
            all(isinstance(item, dict) and 'score' in item and 'label' in item for item in results[0])):
        print("Warning: Unexpected output format from emotion_classifier. Returning default emotion scores.")
        return {
            "top_3_emotions": {},
            "manipulation_components": {"fear": 0, "anger": 0, "sadness": 0}
        }

    emotions = sorted(results[0], key=lambda x: x['score'], reverse=True)
    top_3 = emotions[:3]

    # Extract emotion values
    emotion_dict = {e['label']: e['score'] for e in top_3}

    # For manipulation score (Fear, Anger, Sadness)
    fear = next((e['score'] for e in results[0] if e['label'] == 'fear'), 0)
    anger = next((e['score'] for e in results[0] if e['label'] == 'anger'), 0)
    sadness = next((e['score'] for e in results[0] if e['label'] == 'sadness'), 0)

    return {
        "top_3_emotions": emotion_dict,
        "manipulation_components": {"fear": fear, "anger": anger, "sadness": sadness}
    }

In [53]:
def output_label(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not Fake News"

In [51]:
import math

def manual_testing(news):
    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_xv_test = vectorization.transform(new_def_test["text"])

    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    pred_GB = GB.predict(new_xv_test)
    pred_RF = RF.predict(new_xv_test)

    emotion_results = get_emotion_scores(news)

    fear = emotion_results["manipulation_components"]["fear"]
    anger = emotion_results["manipulation_components"]["anger"]
    sadness = emotion_results["manipulation_components"]["sadness"]

    # Advanced manipulation formula (non-linear, weighted)
    def compute_manipulation_score(fear, anger, sadness):
        # Weights based on psychological studies on emotional manipulation
        weighted_sum = (0.5 * fear) + (0.3 * anger) + (0.2 * sadness)

        # Apply a sigmoid-like curve for realism (scale and shape control)
        scaled = 1 / (1 + math.exp(-10 * (weighted_sum - 0.3)))  # threshold ~0.3
        return round(scaled * 100, 2)

    manipulation_score = compute_manipulation_score(fear, anger, sadness) if pred_LR[0] == 0 else 0

    print("\n\n🧠 Emotion Breakdown (Top 3):")
    for emotion, score in emotion_results["top_3_emotions"].items():
        print(f"{emotion}: {round(score * 100, 2)}%")

    print("\n⚠️ Manipulation Score:", manipulation_score)

    print("\n🔍 Predictions:")
    print("LR Prediction:", output_label(pred_LR[0]))
    print("DT Prediction:", output_label(pred_DT[0]))
    print("GB Prediction:", output_label(pred_GB[0]))
    print("RF Prediction:", output_label(pred_RF[0]))

In [54]:
new = input("Enter the news: ")
manual_testing(new)

Enter the news: 21st Century Wire says As 21WIRE predicted in its new year s look ahead, we have a new  hostage  crisis underway.Today, Iranian military forces report that two small riverine U.S. Navy boats were seized in Iranian waters, and are currently being held on Iran s Farsi Island in the Persian Gulf. A total of 10 U.S. Navy personnel, nine men and one woman, have been detained by Iranian authorities. NAVY STRAYED: U.S. Navy patrol boat in the Persian Gulf (Image Source: USNI)According to the Pentagon, the initial narrative is as follows: The sailors were on a training mission around noon ET when their boat experienced mechanical difficulty and drifted into Iranian-claimed waters and were detained by the Iranian Coast Guard, officials added. The story has since been slightly revised by White House spokesman Josh Earnest to follow this narrative:The 2 boats were traveling en route from Kuwait to Bahrain, when they were stopped and detained by the Iranians.According to USNI, search and rescue teams from the Harry S. Truman Strike group were scrambled to aid the crew but stopped short after the crew was taken by the Iranians. We have been in contact with Iran and have received assurances that the crew and the vessels will be returned promptly,  Pentagon spokesman Peter Cook told AP. According to Persian Gulf TV: Farsi Island is one of the Iranian islands in the Persian Gulf, Bushehr province of Iran. There is an IRGC Navy base on this Island. The island has an area of about 0.25 km  and is completely restricted to public, due to top secret governmental activities. According to NBC News, U.S. State Department is in touch with Tehran officials and the Iranians recognize that the U.S. Navy straying off course was a mistake, and that the sailors will be released  within hours.  WAR INC: CNN s Wolf Blitzer wasted no time in ramping-up talk of military tension with Israeli-financed neocon Senator Tom Cotton.Neocon StuntAlready, the U.S. media, including CNN and FOX, are running with the talking point that,  this could not have come at a worse time for President Obama right before tonight s State Of Union speech, when he s trying to prove to the American people that Iran is a country that can be trusted to implement the historic nuclear deal. This latest Naval  controversy  also comes days before the implementation phase of the Iran Nuclear Deal. To say this is a coincidence might be naive.That said, could GOP and Israel-aligned members of the Pentagon or intelligence establishment have helped to engineer today s bizarre  mini-crisis  in order to help weaken U.S.-Iran relations, and by extension, Obama s controversial Iranian Nuclear Deal?This looks likely to be the case, as evidenced by the quick appearance of the Israel Lobby-sponsored, pro-war U.S. Senator Tom Cotton (R), placed by CNN to direct aggressive U.S. military talking points live on air as the story broke today. Cotton (photo, left) immediately called the event  hostile  and blamed Iran for the U.S. boat drifting into Iranian waters, and then blamed the  crisis  on President Obama, who he claims,  has emboldened the Iranian aggression. Cotton then goes on to tell a giant lie, on which his media handler, CNN s Wolf Blitzer, does not even blink, much less challenge Cotton s imaginary statement: The Iranians, who are largely responsible for killing our (American) soldiers in Iraq and Afghanistan. Cotton then went on to threaten Iran, saying that: These sailors and both vessels  need to be immediately released. If they are not released, then the Iran (nuclear) deal should not go forward, and military force will be on the table to retaliate for this act of aggression.  Cotton then proceeded to give a veiled (nuclear?) threat to Iran, saying that,  All (military) options should be on the table.  Would Washington s top operatives go so far as to engineer or exacerbate an international crisis such as this   by dispatching the boats off course, knowing full-well that Iran would not harm U.S. personnel, but using the incident to injure a lame duck? The answer is  yes , and they ve done it before In 1979, 52 American diplomats and citizens were held hostage for 444 days in what became known as the Iranian Hostage Crisis, which just happened to take place during a US presidential election cycle, with then president Jimmy Carter (D) running for reelection against challenger Ronald Reagan (R). The crisis, including a horrific failed rescue attempt, was used against Carter in the media. According to reports at the time Reagan campaign operatives had managed to do a backdoor deal with the elements of the new Iranian regime to  hold-off  releasing the hostages until after the election. In the end, Reagan won and took credit for that  victory .Not surprisingly, at the end of his prearranged CNN segment, Cotton invoked the  feckless foreign policy  of Jimmy Carter which  caused  the 1979 Iran Hostage Crisis, and compared that to President Obama s current policy.Of all the U.S. Officials CNN could have brought in on  short notice , they chose Senator Tom Cotton, the most hawkish and closest aligned to Israel. Clearly, this looks like a neocon stunt.Stay tuned for more updates.READ MORE IRAN NEWS AT: 21st Century Wire Iran Files
Warning: Unexpected output format from emotion_classifier. Returning default emotion scores.


🧠 Emotion Breakdown (Top 3):

⚠️ Manipulation Score: 4.74

🔍 Predictions:
LR Prediction: Fake News
DT Prediction: Fake News
GB Prediction: Fake News
RF Prediction: Fake News

In [ ]:
import joblib

# Save TF-IDF vectorizer
joblib.dump(vectorization, "vectorizer.pkl")

# Save all models
joblib.dump(LR, "logistic_model.pkl")
joblib.dump(DT, "decision_tree.pkl")
joblib.dump(GB, "gradient_boosting.pkl")
joblib.dump(RF, "random_forest.pkl")

In [ ]:
from google.colab import files
files.download("vectorizer.pkl")
files.download("logistic_model.pkl")
files.download("decision_tree.pkl")
files.download("gradient_boosting.pkl")
files.download("random_forest.pkl")

In [55]:
import pickle

In [56]:
with open("logistic_regression.pkl", "wb") as f:
    pickle.dump(LR, f)

In [57]:
with open("decision_tree.pkl", "wb") as f:
    pickle.dump(DT, f)

In [58]:
with open("gradient_boosting.pkl", "wb") as f:
    pickle.dump(GB, f)

In [59]:
with open("random_forest.pkl", "wb") as f:
    pickle.dump(RF, f)

In [60]:
with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorization, f)

In [61]:
emotion_classifier = pipeline(
    "text-classification",
    model="bhadresh-savani/distilbert-base-uncased-emotion",
    return_all_scores=True
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [62]:
emotion_classifier.model.save_pretrained("emotion_model")
emotion_classifier.tokenizer.save_pretrained("emotion_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('emotion_model/tokenizer_config.json', 'emotion_model/tokenizer.json')

In [63]:
from google.colab import files

files.download("logistic_regression.pkl")
files.download("decision_tree.pkl")
files.download("gradient_boosting.pkl")
files.download("random_forest.pkl")
files.download("tfidf_vectorizer.pkl")

In [64]:
!zip -r emotion_model.zip emotion_model

  adding: emotion_model/ (stored 0%)
  adding: emotion_model/model.safetensors (deflated 8%)
  adding: emotion_model/tokenizer_config.json (deflated 43%)
  adding: emotion_model/tokenizer.json (deflated 71%)
  adding: emotion_model/config.json (deflated 51%)

In [65]:
files.download("emotion_model.zip")